[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "chatool"
dynamic = ["version"]
description = "Chat Tools"
readme = "README.md"
authors = [
    {name = "Jiau Zhang", email = "jiauzhang@163.com"},
]
classifiers = [
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
]
keywords = [
    'Artificial Intelligence',
]
requires-python = ">=3.10"
dependencies = [
    'chatchat>=0.4.9',
    'conippets>=0.1.16',
]

[project.scripts]
chatool = "chatool.__main__:main"

[project.urls]
Homepage = "https://github.com/jiauzhang/chatool"

[tool.hatch.version]
path = "chatool/version.py"

[tool.hatch.build.targets.wheel]
packages = ["chatool"]

[project.optional-dependencies]
dev = ["pytest>=8.3.4"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = ["tests"]
